config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  mount_uploader :image, ImagesUploader
  serialize :image, JSON

  validates :image, file_size: { less_than: 10.megabytes }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos, -> { order('created_at DESC') }


  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :fullname, presence: true, length: { maximum: 50 }
  has_many :rooms

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    user || where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fullname = auth.info.name
      user.image = auth.info.image
      user.uid = auth.uid
      user.provider = auth.provider

      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[fullname ])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[fullname phone_number description])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      flash[:error] = 'There was an error logining to Google, please try again later'
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    if params[:images]
      params[:images].each do |img|
        flash[:error] = 'Something went wrong' unless @room.photos.create(image: img)
      end
      @photos = @room.photos
      redirect_back(fallback_location: request.referer, notice: 'Saved')
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @room = @photo.room
    @photo.image.file.delete
    @photo.destroy
    @photos = Photo.where(room_id: @room.id)
    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :send_rooms, except: %i[create new index]
  before_action :authenticate_user!, except: %i[show]
  before_action :is_authorised, only: %i[listing pricing description photo_upload amenities location update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: 'Saved ....'
    else
      flash[:error] = 'Something went wrong'
      render :new
    end
  end

  def show; end

  def listing; end

  def pricing; end

  def description; end

  def photo_upload
    @photos = @room.photos
  end

  def amenities; end

  def location; end

  def update
    new_params = room_params
    new_params = room_params.merge(active: true) if is_ready_room
    
    if @room.update(new_params)
      flash[:success] = 'Saved'
    else
      flash[:error] = 'Something Went wrong'
    end
    redirect_back(fallback_location: request.referer)
  end

  private

  def send_rooms
    @room = Room.find(params[:id])
  end

  def is_authorised
    redirect_to root_url, error: "You don't have permission" unless current_user.id == @room.user_id
  end

  def is_ready_room
    !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room, :listing_name, :summary,
                                 :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image && user.provider != 'google_oauth2'
      user.image.concat('&type=large')
    elsif user.provider == 'google_oauth2'
      user.image
    else
      gravatar_id = Digest::MD5.hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?s=150"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbCloneFullstack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/messages'%>
    <div class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br/>
  <br/>
  <div class="row">
    <% @photos.each do |photo| %>
      <div class="col-md-3">
        <div class="card">
          <div class="card-header preview">
            <%= image_tag photo.image.thumbnail.url() %>
          </div>
          <div class="card-body">
            <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list'%>")
<% if @room.photos.blank? %>
  $('#photo_check').hide();
<% end %>
<% if !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
  $('#publish_button').attr('disabled', false);
<% else %>
  $('#publish_button').attr('disabled', true);
<% end %>

app/views/rooms/_room_sidebar.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank?  %>
      <span id="photo_check" class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        Amenities
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_for @room do |f| %>
                <div class="row form-group">
                  <div class="col-md-4">
                    <%= f.check_box :is_tv %> TV
                  </div>
                  <div class="col-md-4">
                    <%= f.check_box :is_kitchen %> Kitchen
                  </div>
                  <div class="col-md-4">
                    <%= f.check_box :is_internet %> Internet
                  </div>
                </div>
                <div class="row form-group">
                  <div class="col-md-4">
                    <%= f.check_box :is_heating %> Heating
                  </div>
                  <div class="col-md-4">
                    <%= f.check_box :is_air %> Air Conditioning
                  </div>
                </div>
                <br/>
                <br/>
                <div class="text-center">
                  <%= f.submit "Save", class: "btn btn-form" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        Description
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_for @room do |f| %>
                <div class="row">
                  <div class="form-group">
                    <label>Listing name</label>
                    <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="row">
                  <div class="form-group">
                    <label>Summary</label>
                    <%= f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="text-center">
                  <%= f.submit "Save", class: "btn btn-form" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header py-2 px-3">
        Listing
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_for @room do |f| %>
                <div class="row">
                  <div class="col-md-4 select">
                    <div class="form-group">
                      <label>Home Type</label>
                      <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                id: "home_type", prompt: "Select...", class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-4 select">
                    <div class="form-group">
                      <label>Room Type</label>
                      <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                id: "room_type", prompt: "Select...", class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-4 select">
                    <div class="form-group">
                      <label>Accommodate</label>
                      <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "accommodate", prompt: "Select...", class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-4 select">
                    <div class="form-group">
                      <label>Bedrooms</label>
                      <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bed_room", prompt: "Select...", class: "form-control" %>
                    </div>
                  </div>
                  <div class="col-md-4 select">
                    <div class="form-group">
                      <label>Bathrooms</label>
                      <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bath_rooms", prompt: "Select...", class: "form-control" %>
                    </div>
                  </div>
                </div>
                <div><%= f.submit "Save", class: "btn btn-normal" %></div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        Loacations
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_for @room do |f| %>
                <div class="row">
                  <div class="form-group">
                    <label>Address</label>
                    <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true, id: "autoaddress" %>
                  </div>
                </div>
                <div class="text-center">
                  <%= f.submit "Save", class: "btn btn-form" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="card">
  <div class="card-header p-2">
    Create your beautiful place
  </div>
  <div class="panel-body py-3 rounded-bott">
    <div class="container">
      <%= form_for @room do |f| %>
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                            id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                            id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accommodate</label>
              <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "accomodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bath_rooms", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        </div>
        <div><%= f.submit "Create My Room", class: "btn btn-normal" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        Photos
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <!-- photos Upload here-->
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true, id: 'file-upload' %>
                    </span>
                  </div>
                </div>
                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-normal", id: "img-upload" %>
                </div>
              <% end %>
            </div>
          </div>
          <div id="photos"><%= render 'photos/photos_list' %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(
    function(){
        $('#img-upload').attr('disabled',true);
        $('#file-upload').change(
            function(){
                if ($(this).val()){
                    $('#img-upload').removeAttr('disabled');
                }
                else {
                    $('#img-upload').attr('disabled',true);
                }
            });
    });
</script>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_sidebar' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header p-2">
        Pricing
      </div>
      <div class="panel-body py-3">
        <div class="container">
          <div class="row">
            <div class="col-md-10 offset-md-1">
              <%= form_for @room do |f| %>
                <div class="row">
                  <div class="form-group">
                    <label>Price</label>
                    <%= f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="text-center">
                  <%= f.submit "Save", class: "btn btn-form" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<h1>Rooms#Show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

app/views/shared/_devisealert.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      AirBnB Clone
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "rounded-circle avatar-small" %>&nbsp;
              <b><%= current_user.fullname %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if false %>
                <li><%= link_to "Manage Listing", rooms_path %></li>
                <li><%= link_to "List Your Space", new_room_path %></li>
                <li><%= link_to "Your Reservations", your_reservations_path %></li>
                <li><%= link_to "Your Trips", your_trips_path %></li>
              <% end %>
              <li class="dropdown-item">
                sdsdds
              </li>
              <li role='separator' class="divider"></li>
              <li>
                <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                  <div class="fa fa-cog"></div>
                  <b>Account settings</b>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <div class="fa fa-sign-out-alt"></div>
                  <b>Sign out</b>
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag avatar_url(@user), class: "avatar-full" %>
    <div class="card">
      <div class="card-header p-2 rounded-top">
        Verification 
      </div>
      <div class="panel-body p-3 rounded-bottom">
        Email Address <br/>
        Phone Number <br/>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>